/-
Copyright (c) 2026 The slopetale Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Proetale.Algebra.WeaklyEtale
import Proetale.Algebra.WeakDimension
import Proetale.Algebra.WeaklyEtaleField
import Proetale.Mathlib.RingTheory.WeaklyEtale.TensorSelf
import Proetale.Mathlib.RingTheory.WeaklyEtale.Subalgebra
import Mathlib.RingTheory.Unramified.Field
import Mathlib.FieldTheory.Separable
import Mathlib.RingTheory.Algebraic.Integral
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.IntermediateField.Algebraic
import Mathlib.RingTheory.PolynomialAlgebra
import Mathlib.RingTheory.Flat.FaithfullyFlat.Basic
import Mathlib.RingTheory.Artinian.Module
import Mathlib.RingTheory.SimpleModule.Basic
import Mathlib.RingTheory.Ideal.Cotangent

/-!
# Weakly étale field extensions

Stacks tag [092P] (`lem:flat-tensor-over-field-imples-algebraic`): if `L / K` is an
extension of fields and the multiplication `L ⊗[K] L → L` is flat (equivalently
`Algebra.WeaklyEtale K L`), then `L` is a separable algebraic extension of `K`.

## Main result

* `Algebra.WeaklyEtale.isSeparable_algebraic_of_isField` —
  a weakly étale extension between fields is separable algebraic.

## Proof sketch (Stacks 092P)

Let `μ : L ⊗[K] L → L` denote multiplication; by assumption `μ` is flat. Because
`L` is a field and `μ(1 ⊗ a) = a`, the map `μ` is also surjective, so its kernel
`J` is generated by elements of the form `1 ⊗ a - a ⊗ 1` for `a ∈ L`. The
flatness of `μ` (a flat surjection between commutative rings) forces
`J = J²` (cf. `Algebra.WeaklyEtale.formallyUnramified_of_flat`). Combined with
the fact that `L ⊗[K] L` is reduced (a consequence of weakly-étale-over-field
via `Algebra.FormallyUnramified.isReduced_of_field`), one shows that the
diagonal `Spec L ↪ Spec (L ⊗[K] L)` is both open and closed.

Pulling back this clopen subscheme along the map `Spec L → Spec K[X]` sending
`X` to any `a ∈ L` produces a non-trivial idempotent of `L[X] ≅ K[X] ⊗[K] L`
that picks out the point `X = a`. Since `L[X]` is an integral domain and its
only idempotents up to localisation are governed by polynomial factorisations,
this forces `a` to be a root of some polynomial in `K[X]`, hence algebraic
over `K`.

Once `L / K` is algebraic, separability follows: each `K(a)` is finite (hence
`EssFiniteType`) over `K`, and `L ⊗[K] L → L` flat implies the same for
`K(a) ⊗[K] K(a) → K(a)` after restriction. Applying
`Algebra.FormallyUnramified.iff_isSeparable` to each `K(a)` shows every
element is separable, so `L / K` is separable.

Full details: [Stacks 092P](https://stacks.math.columbia.edu/tag/092P).
-/

universe u

open scoped TensorProduct
open Algebra

namespace Algebra.WeaklyEtale

variable (K L : Type u) [Field K] [Field L] [Algebra K L]

/-- The multiplication map `L ⊗[K] L → L` is surjective for fields (in fact, for any
nontrivial `K`-algebra `L` admitting a unit on the right). This is a trivial observation:
`(1 ⊗ x) ↦ x`. -/
lemma surjective_lmul'_of_field :
    Function.Surjective (Algebra.TensorProduct.lmul' (R := K) (S := L)) := by
  intro x
  exact ⟨1 ⊗ₜ x, by simp⟩

/-- If `L / K` is weakly étale between fields, then `L` is formally unramified over `K`.
This is immediate from the general `Algebra.WeaklyEtale ⇒ Algebra.FormallyUnramified`
instance, restated here for convenience. -/
lemma formallyUnramified_of_isField [Algebra.WeaklyEtale K L] :
    Algebra.FormallyUnramified K L :=
  inferInstance

/-- If `L / K` is weakly étale between fields and `a ∈ L`, then the element
`1 ⊗ a - a ⊗ 1 ∈ L ⊗[K] L` lies in the kernel of multiplication. -/
lemma sub_mem_ker_lmul' (a : L) :
    (1 ⊗ₜ[K] a - a ⊗ₜ[K] 1 : L ⊗[K] L) ∈
      RingHom.ker (Algebra.TensorProduct.lmul' (R := K) (S := L)).toRingHom := by
  simp [RingHom.mem_ker]

/-- Helper (iter-020 scaffolding) for the `δ ≠ 0` substantive case of
`isSeparable_algebraic_of_isField` (Stacks [092P]). Given a weakly étale
extension of fields `K → L` and `a ∈ L` with `1 ⊗ a ≠ a ⊗ 1` in `L ⊗_K L`,
`a` is algebraic over `K`.

Proof strategy (Stacks [092K] route, iter-020 pivot from polyEquivTensor):

1. Form the K-subalgebra `Aa := Algebra.adjoin K {a} ⊆ L`.
2. **Descent step (the residual gap)**: show `K → Aa` is weakly étale.
   This is the field-to-field special case of Stacks 092K (weakly étale
   subalgebras). One direct approach: `K → L` weakly étale + `Aa → L` flat
   (automatic since `L` is `Aa`-torsion-free as a field overextension of
   either `K[X]` or a finite field extension `K(a)`); but flat-descent of
   weakly étale requires faithful flatness, which fails when `a` is
   transcendental (`K[X] → L` is not faithfully flat). The actual descent
   goes via Kähler differentials / formally unramified directly: the
   inclusion `Aa ⊗_K Aa ↪ L ⊗_K L` is K-flat-injective, and idempotency
   of `ker μ_L` should restrict to idempotency of `ker μ_{Aa}` after a
   careful argument inside the subring.
3. From step 2: `Aa ⊗_K Aa → Aa` is flat ⇒ `ker μ_{Aa}` is idempotent
   (by `Algebra.FormallyEtale.iff_of_surjective` applied to `μ_{Aa}`).
4. Case-split on `a` transcendental vs algebraic.
   * `a` transcendental: `Aa ≅ K[X]` so `Aa ⊗_K Aa ≅ K[X, Y]` (domain).
     `ker μ_{Aa}` is the principal ideal `(X - Y)`. By
     `Ideal.isIdempotentElem_iff_eq_bot_or_top` (which requires the
     domain hypothesis), `(X - Y) = ⊥` or `⊤`. Both impossible:
     `X - Y ≠ 0` (so `≠ ⊥`), and `1 ∉ (X - Y)` (so `≠ ⊤`).
   * `a` algebraic: done by definition of `IsAlgebraic`.

The residual gap is step 2 (the descent). Once that helper lands (likely
as a new file `Proetale/Mathlib/RingTheory/WeaklyEtale/Subalgebra.lean`),
steps 3–4 are mechanical. -/
private theorem isAlgebraic_of_isField_aux (a : L) [Algebra.WeaklyEtale K L]
    (_hδ_ne : (1 ⊗ₜ[K] a - a ⊗ₜ[K] 1 : L ⊗[K] L) ≠ 0) :
    IsAlgebraic K a := by
  -- iter-099 structured-reduction scaffold (substantive sorry isolated to the
  -- single residual obligation `hWE_A`).
  --
  -- Strategy: set `A := Algebra.adjoin K {a}` ⊆ L. The subring `A` is of finite
  -- type over `K` (singleton-generated), hence `EssFiniteType`. Once we know
  -- `K → A` is weakly étale, `Algebra.FormallyUnramified.iff_isSeparable`
  -- supplies `IsSeparable K A`, which transports across the inclusion `A ↪ L`
  -- to give integrality (hence algebraicity) of `a`.
  --
  -- The substantive residual obligation `hWE_A : Algebra.WeaklyEtale K A` is
  -- the Stacks 092K subalgebra-descent step, formalised in
  -- `Proetale/Mathlib/RingTheory/WeaklyEtale/Subalgebra.lean` as
  -- `Algebra.WeaklyEtale.adjoin_singleton`. That file imports this one, so
  -- invoking `adjoin_singleton` here would induce a circular import. Both
  -- the descent itself and any refactor that breaks the cycle (e.g., moving
  -- `absolutelyFlat_tensor_self`/`isReduced_tensor_self` to a deeper module
  -- so `Subalgebra.lean` no longer needs to import `FieldExtension.lean`)
  -- are autonomous-loop-deadlocked Phase 4 obstructions per `PROGRESS.md`.
  --
  -- Caveat on the chain below: when `a` is transcendental, `A = K[a]` is *not*
  -- a field, so the `iff_isSeparable` step (which requires `[Field A]`)
  -- additionally needs that `A` is a field — itself equivalent to `a` algebraic.
  -- The blueprint sidesteps this by using `adjoin_singleton` to deduce that
  -- `A ⊗_K A → A` has idempotent kernel, then runs the domain-vs-idempotent
  -- contradiction in `K[X,Y]` (Stacks 092K wrap-up). The scaffold below
  -- preserves the `EssFiniteType` setup so that *if* the descent step lands
  -- (resolving the Phase 4 deadlock), only the final `IsField A`/contradiction
  -- step remains to fully close the helper.
  classical
  let A : Subalgebra K L := Algebra.adjoin K ({a} : Set L)
  haveI : Algebra.FiniteType K A :=
    Algebra.FiniteType.adjoin_of_finite (Set.finite_singleton a)
  haveI : Algebra.EssFiniteType K A := Algebra.EssFiniteType.of_finiteType K A
  -- iter-127 closure: invoke the cycle-free `adjoin_singleton` lemma in
  -- `Subalgebra.lean` (its sole residual sorry — the `FormallyUnramified L
  -- (L⊗A')` obligation — is consumed transitively here).
  haveI hWE_A : Algebra.WeaklyEtale K A := Algebra.WeaklyEtale.adjoin_singleton K L a
  haveI hFU_A : Algebra.FormallyUnramified K A := inferInstance
  -- The kernel `KaehlerDifferential.ideal K A = ker μ_A` is finitely generated
  -- (A is EssFiniteType) and idempotent (FormallyUnramified ⇔ Subsingleton
  -- cotangent ⇔ idempotent kernel).
  have hker_fg : (KaehlerDifferential.ideal K A).FG := KaehlerDifferential.ideal_fg K A
  have hker_idem : IsIdempotentElem (KaehlerDifferential.ideal K A) :=
    (Ideal.cotangent_subsingleton_iff _).mp
      Algebra.FormallyUnramified.subsingleton_kaehlerDifferential
  -- Suppose `a` is not algebraic; we derive a contradiction. The strategy:
  -- if `a` is transcendental, `A ≅ K[X]` so `A ⊗_K A ≅ K[X][Y]` is an integral
  -- domain. Then by `Ideal.isIdempotentElem_iff_eq_bot_or_top`,
  -- `ker μ_A ∈ {⊥, ⊤}`. Both alternatives lead to contradictions:
  --   * `⊥`: the diagonal `1 ⊗ a - a ⊗ 1` lies in `ker μ_A`, hence is zero in
  --     `A ⊗ A`; pushed forward along the K-flat injection `A ⊗ A ↪ L ⊗ L`,
  --     this contradicts `_hδ_ne`.
  --   * `⊤`: then `1 ∈ ker μ_A`, but `μ_A 1 = 1 ≠ 0`.
  by_contra h_not_alg
  -- Build the K-algebra iso `K[X] ≃ₐ[K] A` from injectivity of `aeval a`.
  have h_aeval_inj : Function.Injective (Polynomial.aeval a : Polynomial K →ₐ[K] L) :=
    transcendental_iff_injective.mp h_not_alg
  have hrange : (Polynomial.aeval a : Polynomial K →ₐ[K] L).range = A :=
    (Algebra.adjoin_singleton_eq_range_aeval K a).symm
  let φ : Polynomial K ≃ₐ[K] A :=
    (AlgEquiv.ofInjective (Polynomial.aeval a : Polynomial K →ₐ[K] L) h_aeval_inj).trans
      (Subalgebra.equivOfEq _ A hrange)
  -- Tensor `φ` with itself, then identify `K[X] ⊗_K K[X] ≃ K[X][Y]` via
  -- `polyEquivTensor`. The latter is a domain because `K[X]` is.
  let θ : A ⊗[K] A ≃ₐ[K] Polynomial K ⊗[K] Polynomial K :=
    Algebra.TensorProduct.congr φ.symm φ.symm
  let σ : Polynomial K ⊗[K] Polynomial K ≃ₐ[K] Polynomial (Polynomial K) :=
    (polyEquivTensor K (Polynomial K)).symm
  haveI hdom_AA : IsDomain (A ⊗[K] A) :=
    (θ.trans σ).toRingEquiv.toMulEquiv.isDomain _
  -- Dichotomy in a domain: idempotent FG ideal is `⊥` or `⊤`.
  rcases (Ideal.isIdempotentElem_iff_eq_bot_or_top _ hker_fg).mp hker_idem with hbot | htop
  · -- Case `ker μ_A = ⊥`: the diagonal `1 ⊗ aA - aA ⊗ 1` is in the kernel,
    -- hence equals zero in `A ⊗ A`. The K-algebra inclusion `A ↪ L` induces
    -- a K-algebra map `A ⊗ A → L ⊗ L` carrying this diagonal to the original
    -- `δ`, which is nonzero — contradiction.
    let aA : A := ⟨a, Algebra.self_mem_adjoin_singleton K a⟩
    have hδA_mem : ((1 : A) ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A) : A ⊗[K] A) ∈
        KaehlerDifferential.ideal K A := by
      rw [KaehlerDifferential.ideal, RingHom.mem_ker]
      show Algebra.TensorProduct.lmul' (R := K) (S := A)
          ((1 : A) ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A)) = 0
      rw [map_sub, Algebra.TensorProduct.lmul'_apply_tmul,
        Algebra.TensorProduct.lmul'_apply_tmul, one_mul, mul_one, sub_self]
    rw [hbot, Ideal.mem_bot] at hδA_mem
    apply _hδ_ne
    have hmap := congrArg
      (f := Algebra.TensorProduct.map (R := K) A.val A.val) hδA_mem
    simp only [map_zero, map_sub, Algebra.TensorProduct.map_tmul,
      map_one, Subalgebra.coe_val] at hmap
    -- `hmap : 1 ⊗ (aA : L) - (aA : L) ⊗ 1 = 0`; this is exactly `δ = 0`.
    show (1 : L) ⊗ₜ[K] a - a ⊗ₜ[K] (1 : L) = 0
    exact hmap
  · -- Case `ker μ_A = ⊤`: then `1 ∈ ker μ_A`, so `μ_A 1 = 1 = 0` in A,
    -- contradicting nontriviality of A.
    have h1_mem : (1 : A ⊗[K] A) ∈ KaehlerDifferential.ideal K A :=
      htop ▸ Submodule.mem_top
    rw [KaehlerDifferential.ideal, RingHom.mem_ker, map_one] at h1_mem
    exact one_ne_zero h1_mem

/-- (Stacks [092P].) If `L / K` is an extension of fields with `K → L` weakly étale,
then `L` is a separable algebraic extension of `K`.

This is the key reduction Stacks 092Q (`Algebra.WeaklyEtale.indEtale_of_isField`)
relies on: the local rings of a weakly étale `K`-algebra `B` are fields, and applying
this lemma to each shows they are separable algebraic over `K`, which then feeds into
the proof that `B` is itself ind-étale.

The proof is the subject of the blueprint section
`lem:flat-tensor-over-field-imples-algebraic` in
`blueprint/src/chapters/more-on-local-structure.tex`. The mathematical strategy is:
flatness of `L ⊗[K] L → L` makes the diagonal clopen in `Spec (L ⊗[K] L)`; pulling
back via `K[X] → L`, `X ↦ a` yields a polynomial relation on each `a ∈ L`. -/
theorem isSeparable_algebraic_of_isField [Algebra.WeaklyEtale K L] :
    Algebra.IsSeparable K L ∧ Algebra.IsAlgebraic K L := by
  -- Step 1: derive `Algebra.FormallyUnramified K L` from `Algebra.WeaklyEtale K L`.
  haveI : Algebra.FormallyUnramified K L := inferInstance
  -- Step 2 (the heart of 092P): show every `a : L` is algebraic over `K`. The blueprint
  -- argument uses the clopen diagonal `Spec L ↪ Spec (L ⊗[K] L)` (which follows from
  -- `L ⊗ L` being absolutely flat, hence reduced + every prime maximal) pulled back
  -- along `K[X] → L`, `X ↦ a` to land an idempotent in `K[X] ⊗[K] L ≃ L[X]` whose
  -- support pins down a polynomial relation `p(a) = 0`.
  --
  -- The clopenness ingredients are now available (`absolutelyFlat_tensor_self`,
  -- `isReduced_tensor_self`, `sub_mem_ker_lmul'`), but the precise extraction of
  -- the polynomial relation requires the `polyEquivTensor` (`K[X] ≃ K ⊗ K[X]`,
  -- not yet wired here in the K[X] ⊗ L ≃ L[X] direction) together with a
  -- domain-ness argument on `L[X]`, which has not yet been formalised.
  have h_alg : Algebra.IsAlgebraic K L := by
    refine ⟨fun a => ?_⟩
    -- For each `a ∈ L`, the element `δ := 1 ⊗ a - a ⊗ 1 ∈ L ⊗ L` lies in `ker (lmul')`,
    -- which is itself an idempotent ideal in the absolutely-flat ring `L ⊗ L`.
    -- The required polynomial relation `p(a) = 0` is extracted by pulling back the
    -- clopen idempotent along the ring map `K[X] → L`, `X ↦ a`.
    -- See blueprint `lem:flat-tensor-over-field-imples-algebraic`.
    --
    -- Setup: the principal ideal `(δ)` is f.g., hence by `Ring.AbsolutelyFlat`
    -- (= every f.g. ideal is generated by an idempotent — `Ideal.isIdempotentElem_iff_of_fg`),
    -- there exists an idempotent `e ∈ L ⊗ L` with `Ideal.span {δ} = Ideal.span {e}`.
    -- The K-subalgebra `K[e]` is `K[X]/(X² - X) ≅ K × K`. Pulling back via the
    -- L-algebra map `tensorEvalRight K L a : L[X] → L ⊗ L` (already defined here)
    -- yields a non-trivial idempotent in `L[X]`. Since `L[X]` is a domain, the only
    -- idempotents are `0` and `1`, so the pullback is constant. This forces a
    -- polynomial relation on `a`.
    --
    -- The detailed extraction (relating the polynomial obtained to a non-trivial
    -- annihilator of `a` over `K`) is a substantial Stacks 092P argument and is
    -- not finished here. The framework variables are set up below.
    -- Abbreviate the diagonal element δ := 1 ⊗ a - a ⊗ 1.
    set δ : L ⊗[K] L := 1 ⊗ₜ[K] a - a ⊗ₜ[K] 1 with hδ_def
    have hδ : δ ∈
        RingHom.ker (Algebra.TensorProduct.lmul' (R := K) (S := L)).toRingHom :=
      sub_mem_ker_lmul' K L a
    -- The principal ideal generated by `δ`. It is f.g. (in fact principal).
    let Iδ : Ideal (L ⊗[K] L) := Ideal.span {δ}
    have hIδ_fg : Iδ.FG := ⟨{δ}, by simp [Iδ]⟩
    -- Step (i): `Iδ` is idempotent. Proof: the quotient map `q : L⊗L → L⊗L/Iδ`
    -- is surjective; it is also flat because `L⊗L` is absolutely flat (every module is
    -- flat, in particular `L⊗L/Iδ` is `L⊗L`-flat). Apply
    -- `exists_eq_mul_of_surjective_flat` to `δ ∈ ker q`: there exists `z ∈ L⊗L` with
    -- `q(z) = 1` and `z·δ = 0`. From `q(z) = 1` we get `z - 1 ∈ Iδ`, say
    -- `z - 1 = r·δ`. Combined with `z·δ = 0` we obtain `δ + r·δ² = 0`, i.e.
    -- `δ ∈ Iδ²`, hence `Iδ ⊆ Iδ²`.
    have hIδ_idem : IsIdempotentElem Iδ := by
      -- `Iδ` is pure because `L⊗L` is absolutely flat (every quotient is flat).
      haveI : Ring.AbsolutelyFlat (L ⊗[K] L) := absolutelyFlat_tensor_self K L
      haveI : Iδ.Pure := Ring.AbsolutelyFlat.flat Iδ
      exact Ideal.isIdempotentElem_of_pure Iδ
    -- Step (ii): obtain an idempotent generator `e ∈ L⊗L` of `Iδ`.
    obtain ⟨e, he_idem, he_span⟩ :=
      (Ideal.isIdempotentElem_iff_of_fg Iδ hIδ_fg).mp hIδ_idem
    -- `Submodule.span R {e} = Ideal.span {e}` definitionally.
    -- Step (iii): `μ(e) = 0`. Since `e ∈ Iδ = Ideal.span {δ}`, we have `e = δ·s` for
    -- some `s ∈ L⊗L`. Applying `μ` and using `μ(δ) = 0`: `μ(e) = μ(δ)·μ(s) = 0`.
    have he_in_Iδ : e ∈ Iδ := by
      rw [he_span]; exact Submodule.mem_span_singleton_self _
    have hμe : (Algebra.TensorProduct.lmul' (R := K) (S := L)).toRingHom e = 0 := by
      -- e ∈ Iδ ⊆ ker μ.
      have hIδ_subset_ker : Iδ ≤ RingHom.ker
          (Algebra.TensorProduct.lmul' (R := K) (S := L)).toRingHom := by
        rw [show Iδ = Ideal.span {δ} from rfl, Ideal.span_le, Set.singleton_subset_iff]
        exact hδ
      exact hIδ_subset_ker he_in_Iδ
    -- Step (iv): polynomial extraction. We have a non-trivial idempotent `e ∈ L⊗L`
    -- with `(e) = (δ)` and `μ(e) = 0`. We first derive the key consequences of
    -- `e` being idempotent and a generator of `(δ)`.
    --
    -- (a) `1 - e` is also idempotent.
    have he_one_sub : IsIdempotentElem ((1 : L ⊗[K] L) - e) := he_idem.one_sub
    -- (b) `e · (1 - e) = 0` (the standard orthogonality of complementary idempotents).
    have he_orth : e * (1 - e) = 0 := he_idem.mul_one_sub_self
    -- (c) `δ ∈ Iδ = (e)`, so `δ = e · s` for some `s ∈ L⊗L`.
    obtain ⟨s, hs⟩ : ∃ s : L ⊗[K] L, δ = e * s := by
      have hδ_in : δ ∈ Iδ := Ideal.mem_span_singleton_self δ
      rw [he_span, Submodule.mem_span_singleton] at hδ_in
      obtain ⟨s, hs⟩ := hδ_in
      exact ⟨s, by simpa [mul_comm] using hs.symm⟩
    -- (d) Hence `δ · (1 - e) = 0`. Using commutativity of `L ⊗ L`:
    --     `δ · (1 - e) = (e · s) · (1 - e) = (e · (1 - e)) · s = 0`.
    have hδ_one_sub : δ * (1 - e) = 0 := by
      calc δ * (1 - e) = (e * s) * (1 - e) := by rw [hs]
        _ = (e * (1 - e)) * s := by ring
        _ = 0 * s := by rw [he_orth]
        _ = 0 := zero_mul _
    -- (e) Translating (d) via `δ = 1⊗a - a⊗1`:
    --     `(1⊗a)·(1-e) = (a⊗1)·(1-e)` in `L⊗L`.
    have hkey : (1 ⊗ₜ[K] a : L ⊗[K] L) * (1 - e) = (a ⊗ₜ[K] 1 : L ⊗[K] L) * (1 - e) := by
      have := hδ_one_sub
      rw [hδ_def, sub_mul] at this
      exact sub_eq_zero.mp this
    -- The remaining polynomial extraction. The key relation `hkey` says that, after
    -- multiplying by `(1 - e)`, the elements `1 ⊗ a` and `a ⊗ 1` agree in `L ⊗_K L`.
    -- Concretely: in the ring `R₂ := (1-e)·(L⊗L)` (with unit `1-e`), the image of
    -- `1 ⊗ a` equals the image of `a ⊗ 1`, where the latter is the image of `a` under
    -- the canonical section `L → R₂`, `l ↦ (1-e)·(l⊗1)` of the surjection
    -- `μ₂ : R₂ → L`. The K-algebra map `K[X] → L⊗L`, `X ↦ 1⊗a`, composed with the
    -- projection `L⊗L → R₂`, factors as `K[X] → K → R₂`, `X ↦ a` (a scalar in the
    -- L-algebra structure of `R₂`). The kernel of this composite is therefore a
    -- non-trivial K[X]-ideal — once we can detect when the composite K[X] → L⊗L → R₂
    -- yields a polynomial relation that descends to one in K[X] annihilating `a` via
    -- `μ₂ : R₂ → L`. This descent is the residual technical step.
    --
    -- The detailed extraction (linking the relation `(1⊗a - a⊗1)·(1-e) = 0` to a
    -- non-zero polynomial in `K[X]` annihilating `a` over `K`) follows the
    -- "K[X] ⊗_K L ≃ L[X] is a domain" argument from the blueprint
    -- (`lem:flat-tensor-over-field-imples-algebraic`).
    --
    -- We case-split on whether `δ = 0`. The case `δ = 0` (equivalent to `e = 0`
    -- by `Iδ = (e)`) is closed completely via K-linear independence of
    -- `{1, a} ⊗_K {1, a}` (when `a ∉ K`). The substantive case `δ ≠ 0` requires
    -- the polyEquivTensor + domain-of-L[X] reasoning and is left as a typed
    -- `sorry` with full framework in scope.
    by_cases hδ_eq_zero : δ = 0
    · -- Case `δ = 0`: then `1 ⊗ a = a ⊗ 1` in `L ⊗_K L`. By K-linear independence
      -- of the family `(i, j) ↦ ![1, a] i ⊗ ![1, a] j` (which follows from
      -- `{1, a}` being K-linearly independent in `L` when `a ∉ algebraMap K L`,
      -- via `LinearIndependent.tmul_of_flat_left`), we deduce
      -- `a ∈ Set.range (algebraMap K L)`, hence `a` is annihilated by
      -- `X - C k` (with `k ∈ K` the preimage of `a`).
      have h_tmul_eq : (1 ⊗ₜ[K] a : L ⊗[K] L) = a ⊗ₜ[K] 1 := by
        have h_zero : (1 ⊗ₜ[K] a - a ⊗ₜ[K] 1 : L ⊗[K] L) = 0 := by
          rw [← hδ_def]; exact hδ_eq_zero
        exact sub_eq_zero.mp h_zero
      -- Reduce: it suffices to find `k : K` with `algebraMap K L k = a`.
      suffices h_a_in_K : ∃ k : K, algebraMap K L k = a by
        obtain ⟨k, hk⟩ := h_a_in_K
        refine ⟨Polynomial.X - Polynomial.C k, Polynomial.X_sub_C_ne_zero k, ?_⟩
        simp [hk]
      -- Prove by contradiction; suppose `a ∉ range (algebraMap K L)`.
      by_contra h_not_in_K
      simp only [not_exists] at h_not_in_K
      -- Then `{1, a}` is K-linearly independent in `L` (`a ≠ k • 1` for any `k`).
      have hli : LinearIndependent K (![(1 : L), a]) := by
        rw [LinearIndependent.pair_iff' (one_ne_zero (α := L))]
        intro k hk
        apply h_not_in_K k
        rw [Algebra.smul_def, mul_one] at hk
        exact hk
      -- Tensor: the family `(i, j) ↦ ![1, a] i ⊗ ![1, a] j` is also K-linearly
      -- independent (because `L` is K-flat: any field over a subfield is flat).
      have hli2 : LinearIndependent K
          (fun ij : Fin 2 × Fin 2 => (![(1 : L), a] ij.1) ⊗ₜ[K] (![(1 : L), a] ij.2)) :=
        hli.tmul_of_flat_left hli
      -- A linearly independent family is injective as a function on indices.
      have h_inj : Function.Injective (fun ij : Fin 2 × Fin 2 =>
          (![(1 : L), a] ij.1) ⊗ₜ[K] (![(1 : L), a] ij.2)) := hli2.injective
      -- The values at `(0, 1)` and `(1, 0)` are `1 ⊗ a` and `a ⊗ 1`, equal by
      -- `h_tmul_eq`. Injectivity forces `(0, 1) = (1, 0)` — contradiction.
      have h01_eq_10 : ((0 : Fin 2), (1 : Fin 2)) = ((1 : Fin 2), (0 : Fin 2)) := by
        apply h_inj
        simp [h_tmul_eq]
      simp at h01_eq_10
    · -- Case `δ ≠ 0`: substantive case. The polyEquivTensor framework has been
      -- exhausted across iter-017/018/019 (five distinct dead-ends; see
      -- `task_results/.../FieldExtension.lean.md`). iter-020 pivots to the
      -- Stacks 092K route: prove `K → K[a]` weakly étale (subalgebra descent),
      -- then `K[a] ⊗_K K[a] → K[a]` is flat, and in the transcendental case
      -- `K[a] = K[X]`, `K[a] ⊗_K K[a] = K[X, Y]` is a domain, so the kernel
      -- `(X - Y)` of the multiplication map is principal in a domain hence
      -- (by being a flat ideal forced to be idempotent) either 0 or full —
      -- both impossible.
      --
      -- Available scaffolding for the next iteration (all in scope here):
      -- * `δ : L ⊗[K] L` (= `1 ⊗ a - a ⊗ 1`), with `hδ_eq_zero : ¬δ = 0`.
      -- * `e : L ⊗[K] L` idempotent with `Ideal.span {δ} = Ideal.span {e}`
      --   (`he_idem`, `he_span`).
      -- * `hμe : μ(e) = 0`.
      -- * `hkey : (1 ⊗ a) * (1 - e) = (a ⊗ 1) * (1 - e)` in `L ⊗_K L`.
      -- * `hδ_one_sub : δ * (1 - e) = 0`.
      -- * `e ≠ 0` (immediate from `δ ≠ 0` and `(δ) = (e)`).
      --
      -- The residual obligation to close this branch is exactly the descent
      -- step: prove that the principal ideal `(δ)_{Aa ⊗_K Aa}` is idempotent
      -- in `Aa ⊗_K Aa` (where `Aa := Algebra.adjoin K {a}`). The ambient ring
      -- `L ⊗_K L` has `(δ)` idempotent (via `hIδ_idem`), but the principal
      -- ideal in the subring `Aa ⊗_K Aa ↪ L ⊗_K L` is generally smaller and
      -- its idempotency does not transfer directly without the descent.
      --
      -- See `Proetale/Mathlib/RingTheory/WeaklyEtale/Subalgebra.lean` (to be
      -- created) for the planned descent lemma, and the iter-020 plan
      -- (`.archon/iter/iter-020/objectives.md`) for the full strategy.
      exact isAlgebraic_of_isField_aux K L a hδ_eq_zero
  refine ⟨?_, h_alg⟩
  -- Step 3: from algebraicity, derive separability element-by-element. Each `a : L`
  -- is algebraic, so lies in a finite subfield `K⟮a⟯ = IntermediateField.adjoin K {a}`.
  -- We then need `FormallyUnramified K K⟮a⟯` (so that `iff_isSeparable` applies).
  -- The descent from `FormallyUnramified K L` to `FormallyUnramified K K⟮a⟯` along
  -- the (faithfully flat, since `K⟮a⟯` is a field and `L` is a nontrivial extension)
  -- inclusion `K⟮a⟯ ↪ L` is captured below by a private helper, currently with a
  -- typed `sorry` for the Kähler-differential descent argument.
  refine ⟨fun a => ?_⟩
  -- `a` is algebraic (from `h_alg`); package this as `IsIntegral K a`.
  have ha_int : IsIntegral K a := (h_alg.isAlgebraic a).isIntegral
  -- Build the finite intermediate field `K⟮a⟯`.
  let F : IntermediateField K L := IntermediateField.adjoin K ({a} : Set L)
  have hF_fin : FiniteDimensional K F :=
    IntermediateField.finiteDimensional_adjoin (S := ({a} : Set L)) (by simp [ha_int])
  -- `K⟮a⟯` is finite-dimensional over `K`, hence finite type, hence essentially of
  -- finite type.
  haveI : Module.Finite K F := hF_fin
  haveI : Algebra.FiniteType K F := Module.Finite.finiteType F
  haveI : Algebra.EssFiniteType K F := Algebra.EssFiniteType.of_finiteType K F
  -- Faithful flatness of `K → F` (every nontrivial extension of a field is faithfully
  -- flat: `F` is `K`-free, hence flat; nontriviality gives the faithful condition).
  haveI : Module.FaithfullyFlat K F := inferInstance
  -- The hard step: descend `FormallyUnramified K L` along the inclusion `F ↪ L`.
  -- This uses faithful flatness of `F → L` (every nontrivial field extension is
  -- faithfully flat) plus a Kähler-differential argument on the cotangent sequence.
  -- See blueprint `lem:flat-tensor-over-field-imples-algebraic` end-of-proof.
  haveI hFU_F : Algebra.FormallyUnramified K F := by
    -- Strategy: `F ⊗_K F` embeds into the reduced ring `L ⊗_K L`, hence is reduced.
    -- It is also Artinian (finite-dim over the field `K`). A reduced Artinian ring is
    -- semisimple, so every ideal is generated by an idempotent, hence idempotent.
    -- Applied to the Kähler differential ideal, this gives `Subsingleton Ω[F/K]`,
    -- i.e. `FormallyUnramified K F`.
    have hinj_lin : Function.Injective
        (_root_.TensorProduct.map (R := K) F.val.toLinearMap F.val.toLinearMap) :=
      TensorProduct.map_injective_of_flat_flat _ _
        (F.val.injective : Function.Injective ⇑F.val.toLinearMap)
        (F.val.injective : Function.Injective ⇑F.val.toLinearMap)
    have hinj : Function.Injective
        ((Algebra.TensorProduct.map F.val F.val).toRingHom :
          ↥F ⊗[K] ↥F →+* L ⊗[K] L) := hinj_lin
    have hReducedFF : IsReduced (↥F ⊗[K] ↥F) :=
      isReduced_of_injective _ hinj
    haveI : Module.Finite K (↥F ⊗[K] ↥F) := Module.Finite.tensorProduct K ↥F ↥F
    haveI : IsArtinianRing (↥F ⊗[K] ↥F) :=
      .of_finite K (↥F ⊗[K] ↥F)
    haveI : IsSemisimpleRing (↥F ⊗[K] ↥F) :=
      IsArtinianRing.isSemisimpleRing_of_isReduced (↥F ⊗[K] ↥F)
    obtain ⟨e, he, hsp⟩ := IsSemisimpleRing.ideal_eq_span_idempotent
      (KaehlerDifferential.ideal K ↥F)
    have hIdem : IsIdempotentElem (KaehlerDifferential.ideal K ↥F) := by
      show KaehlerDifferential.ideal K ↥F * KaehlerDifferential.ideal K ↥F =
          KaehlerDifferential.ideal K ↥F
      rw [hsp, Ideal.span_singleton_mul_span_singleton, he.eq]
    rw [Algebra.formallyUnramified_iff]
    exact (Ideal.cotangent_subsingleton_iff _).mpr hIdem
  -- Apply `iff_isSeparable` to conclude `Algebra.IsSeparable K F`.
  have hsep_F : Algebra.IsSeparable K F :=
    (Algebra.FormallyUnramified.iff_isSeparable K (L := F)).mp hFU_F
  -- Transfer from `a ∈ F = K⟮a⟯` back to `a` itself in `L`.
  have ha_in_F : a ∈ F := IntermediateField.subset_adjoin _ _ (by simp)
  have hsep_F_elem : IsSeparable K (⟨a, ha_in_F⟩ : F) :=
    Algebra.IsSeparable.isSeparable' _
  rwa [IsSeparable, IntermediateField.minpoly_eq] at hsep_F_elem

end Algebra.WeaklyEtale
