/-
Copyright (c) 2026 The slopetale Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Proetale.Mathlib.RingTheory.WeaklyEtale.FieldExtension
import Mathlib.RingTheory.Ideal.Pure
import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.EssentialFiniteness

/-!
# Weakly étale subalgebras of fields

This file formalises the field-to-field specialisation of Stacks
[092K](https://stacks.math.columbia.edu/tag/092K): if `K → L` is a weakly étale
extension of fields and `a ∈ L`, then the `K`-subalgebra `K[a] = Algebra.adjoin K {a}`
is again weakly étale over `K`.

The bivariate corollary closes the transcendental case of Stacks 092P (the consumer
`Algebra.WeaklyEtale.isAlgebraic_of_isField_aux` in `FieldExtension.lean`): once
`K → K[a]` is weakly étale and `a` is transcendental, `K[a] ⊗_K K[a] ≅ K[X, Y]` is
a domain whose multiplication kernel is the principal ideal `(X − Y)`, which is
neither `⊥` nor `⊤`, contradicting the idempotency forced by formal étaleness.

## Main results

* `Algebra.WeaklyEtale.adjoin_singleton` —
  `K → Algebra.adjoin K {a}` is weakly étale when `K → L` is and `a ∈ L`.

## Proof strategy (Stacks 092K, field-to-field case)

Write `A := Algebra.adjoin K {a}`. Recall `Algebra.WeaklyEtale K A` decomposes into:

1. **Flatness `K → A`**: automatic because `K` is a field; every `K`-module is free,
   hence flat.
2. **Flatness of `μ_A : A ⊗_K A → A`**: since `μ_A` is surjective with finitely
   generated kernel (`KaehlerDifferential.ideal K A` is FG by `EssFiniteType`),
   `RingHom.Flat μ_A` is equivalent to `(ker μ_A).Pure`, which by
   `Ideal.Pure.of_isIdempotentElem` reduces to `IsIdempotentElem (ker μ_A)`.

The idempotency in `A ⊗_K A` is the substantive Stacks 092K piece. It is inherited
from the absolutely flat overring `L ⊗_K L` along the `K`-flat injection
`A ⊗_K A ↪ L ⊗_K L`. iter-021 lands the infrastructure file and the auxiliary
lemmas; the full descent argument remains as a typed `sorry` (its precise strategy
is documented in the proof body).
-/

universe u

open scoped TensorProduct
open Algebra

namespace Algebra.WeaklyEtale

variable (K L : Type u) [Field K] [Field L] [Algebra K L]

section AdjoinSingleton

variable (a : L)

/-- The kernel `KaehlerDifferential.ideal K A` of the multiplication map
`A ⊗_K A → A` is finitely generated when `A = Algebra.adjoin K {a}`, because `A`
is essentially of finite type over `K` (generated by the single element `a`). -/
private lemma kaehler_ideal_fg_adjoin :
    (KaehlerDifferential.ideal K
      (Algebra.adjoin K ({a} : Set L))).FG := by
  haveI : Algebra.FiniteType K (Algebra.adjoin K ({a} : Set L)) :=
    Algebra.FiniteType.adjoin_of_finite (Set.finite_singleton a)
  haveI : Algebra.EssFiniteType K (Algebra.adjoin K ({a} : Set L)) :=
    Algebra.EssFiniteType.of_finiteType K _
  exact KaehlerDifferential.ideal_fg K _

/-- The inclusion `A ⊗_K A → L ⊗_K L` (where `A = Algebra.adjoin K {a}`) is
injective: `K`-flatness of `L` and `A` is automatic since `K` is a field, so the
tensor product of the inclusion `A ↪ L` with itself is injective. -/
private lemma adjoinTensorIncl_injective :
    Function.Injective
      (Algebra.TensorProduct.map
        (Algebra.adjoin K ({a} : Set L)).val
        (Algebra.adjoin K ({a} : Set L)).val :
          _ →ₐ[K] L ⊗[K] L) := by
  have hinj : Function.Injective
      ((Algebra.adjoin K ({a} : Set L)).val : _ → L) := Subtype.val_injective
  exact TensorProduct.map_injective_of_flat_flat _ _ hinj hinj

/-- For `A := Algebra.adjoin K {a}` inside `L`, the kernel of the multiplication
map `μ_A : A ⊗_K A → A` is the principal ideal generated by the diagonal
`δ := 1 ⊗ a - a ⊗ 1`. The "⊇" inclusion (containment) is `μ_A δ = 0`. The "⊆"
direction uses that every element of `A` is built from `a` via K-algebra
operations (`Algebra.adjoin_induction`); each diagonal `1 ⊗ b - b ⊗ 1` reduces
to a multiple of `δ` by telescoping (mem case), additivity, and the
multiplicative split
`1⊗(xy) - xy⊗1 = (1⊗x)(1⊗y - y⊗1) + (1⊗x - x⊗1)(y⊗1)`. -/
private lemma kaehler_ideal_adjoin_singleton_eq_span :
    letI A' : Subalgebra K L := Algebra.adjoin K ({a} : Set L)
    letI aA : A' := ⟨a, Algebra.self_mem_adjoin_singleton K a⟩
    KaehlerDifferential.ideal K A' =
      Ideal.span ({(1 : A') ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A')} :
        Set (A' ⊗[K] A')) := by
  set A' : Subalgebra K L := Algebra.adjoin K ({a} : Set L)
  set aA : A' := ⟨a, Algebra.self_mem_adjoin_singleton K a⟩
  set δ : A' ⊗[K] A' := (1 : A') ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A')
  refine le_antisymm ?_ ?_
  · rw [← KaehlerDifferential.span_range_eq_ideal]
    rw [Ideal.span_le]
    rintro _ ⟨b, rfl⟩
    obtain ⟨b', hb'⟩ := b
    suffices h : ∀ (y : L) (hy : y ∈ Algebra.adjoin K ({a} : Set L)),
        ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A') -
          (⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) ∈ Ideal.span ({δ} : Set (A' ⊗[K] A')) from
      h b' hb'
    intro y hy
    induction hy using Algebra.adjoin_induction with
    | mem x hx =>
      rw [Set.mem_singleton_iff] at hx
      subst hx
      exact Ideal.subset_span (Set.mem_singleton _)
    | algebraMap r =>
      have h0 : (1 : A') ⊗ₜ[K] (⟨algebraMap K L r,
          Subalgebra.algebraMap_mem _ _⟩ : A') -
          (⟨algebraMap K L r,
            Subalgebra.algebraMap_mem _ _⟩ : A') ⊗ₜ[K] (1 : A') = 0 := by
        have hval : (⟨algebraMap K L r,
            Subalgebra.algebraMap_mem _ _⟩ : A') = algebraMap K A' r := rfl
        rw [hval, Algebra.algebraMap_eq_smul_one,
          TensorProduct.tmul_smul, TensorProduct.smul_tmul', sub_self]
      rw [h0]
      exact Ideal.zero_mem _
    | add x y hx hy IHx IHy =>
      have hsum : (⟨x + y, add_mem hx hy⟩ : A') =
          (⟨x, hx⟩ : A') + (⟨y, hy⟩ : A') := rfl
      have heq : (1 : A') ⊗ₜ[K] (⟨x + y, add_mem hx hy⟩ : A') -
          (⟨x + y, add_mem hx hy⟩ : A') ⊗ₜ[K] (1 : A') =
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A') - (⟨x, hx⟩ : A') ⊗ₜ[K] (1 : A')) +
          ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A') - (⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) := by
        rw [hsum, TensorProduct.tmul_add, TensorProduct.add_tmul]
        abel
      rw [heq]
      exact Ideal.add_mem _ IHx IHy
    | mul x y hx hy IHx IHy =>
      have hmul : (⟨x * y, mul_mem hx hy⟩ : A') =
          (⟨x, hx⟩ : A') * (⟨y, hy⟩ : A') := rfl
      have h1 : ((1 : A') ⊗ₜ[K] ((⟨x, hx⟩ : A') * (⟨y, hy⟩ : A')) :
            A' ⊗[K] A') =
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A')) *
            ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A')) := by
        rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one]
      have h2 : (((⟨x, hx⟩ : A') * (⟨y, hy⟩ : A')) ⊗ₜ[K] (1 : A') :
            A' ⊗[K] A') =
          ((⟨x, hx⟩ : A') ⊗ₜ[K] (1 : A')) *
            ((⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) := by
        rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one]
      have heq : (1 : A') ⊗ₜ[K] (⟨x * y, mul_mem hx hy⟩ : A') -
          (⟨x * y, mul_mem hx hy⟩ : A') ⊗ₜ[K] (1 : A') =
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A')) *
            ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A') -
              (⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) +
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A') -
            (⟨x, hx⟩ : A') ⊗ₜ[K] (1 : A')) *
            ((⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) := by
        rw [hmul, h1, h2]
        ring
      rw [heq]
      exact Ideal.add_mem _
        (Ideal.mul_mem_left _ _ IHy)
        (Ideal.mul_mem_right _ _ IHx)
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    show δ ∈ KaehlerDifferential.ideal K A'
    rw [KaehlerDifferential.ideal, RingHom.mem_ker]
    show Algebra.TensorProduct.lmul' (R := K) (S := A')
        ((1 : A') ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A')) = 0
    rw [map_sub, Algebra.TensorProduct.lmul'_apply_tmul,
      Algebra.TensorProduct.lmul'_apply_tmul, one_mul, mul_one, sub_self]

/-- If the kernel of the multiplication map `μ : S ⊗[R] S → S` is a pure ideal,
then `μ : S ⊗[R] S →+* S` is flat. This is the standard step that converts
purity of `KaehlerDifferential.ideal R S` into flatness of `lmul'`. -/
private lemma flat_lmul'_of_pure_ker {R S : Type*} [CommRing R] [CommRing S]
    [Algebra R S] (hpure : (KaehlerDifferential.ideal R S).Pure) :
    (Algebra.TensorProduct.lmul' (R := R) (S := S)).toRingHom.Flat := by
  -- Unfold to `Module.Flat (S⊗S) S` under the `lmul'.toAlgebra` structure.
  rw [RingHom.Flat]
  letI : Algebra (S ⊗[R] S) S :=
    (Algebra.TensorProduct.lmul' (R := R) (S := S)).toRingHom.toAlgebra
  -- Under this algebra structure, `algebraMap (S⊗S) S = lmul'`.
  have h_alg : algebraMap (S ⊗[R] S) S =
      (Algebra.TensorProduct.lmul' (R := R) (S := S)).toRingHom := rfl
  -- `algebraMap` is (S⊗S)-linear (it's the algebraMap!), and surjective.
  have h_sur : Function.Surjective (Algebra.linearMap (S ⊗[R] S) S) := by
    intro x; exact ⟨x ⊗ₜ[R] 1, by simp [Algebra.linearMap, h_alg]⟩
  -- `LinearMap.ker (Algebra.linearMap _ _)` is the underlying submodule of
  -- `KaehlerDifferential.ideal R S`.
  have h_ker_eq : LinearMap.ker (Algebra.linearMap (S ⊗[R] S) S) =
      (KaehlerDifferential.ideal R S).restrictScalars (S ⊗[R] S) := by
    ext x
    simp [Algebra.linearMap, KaehlerDifferential.ideal, RingHom.mem_ker, h_alg]
  -- `LinearMap.quotKerEquivOfSurjective` gives a (S⊗S)-linear iso
  -- `(S⊗S) ⧸ LinearMap.ker(linearMap) ≃ₗ[S⊗S] S`.
  have hsur_iso :
      ((S ⊗[R] S) ⧸ LinearMap.ker (Algebra.linearMap (S ⊗[R] S) S))
        ≃ₗ[S ⊗[R] S] S :=
    LinearMap.quotKerEquivOfSurjective _ h_sur
  -- The underlying submodule of `KaehlerDifferential.ideal R S` (after
  -- `restrictScalars`) equals the LinearMap kernel, so the two quotients
  -- are the same.
  -- `hpure : Module.Flat (S⊗S) ((S⊗S) ⧸ KaehlerDifferential.ideal R S)`.
  -- That `Pure` is `Module.Flat (S⊗S) ((S⊗S) ⧸ I)` where the quotient is
  -- the ideal quotient. We need to transport to the submodule quotient.
  -- For ideals, `(R⧸I)` as a Ring with R-module structure coincides with
  -- the submodule quotient, so the two are definitionally equal.
  have h_flat_quot : Module.Flat (S ⊗[R] S)
      ((S ⊗[R] S) ⧸ LinearMap.ker (Algebra.linearMap (S ⊗[R] S) S)) := by
    rw [h_ker_eq]
    -- Now want `Module.Flat (S⊗S) ((S⊗S) ⧸ ((KaehlerDifferential.ideal R S).restrictScalars _))`.
    -- This is the same as `Pure (KaehlerDifferential.ideal R S)` up to identification.
    exact hpure
  exact Module.Flat.of_linearEquiv hsur_iso.symm

/-- **Stacks [092K], field-to-field specialisation.**

If `K → L` is a weakly étale extension of fields and `a ∈ L`, then the
`K`-subalgebra `K[a] = Algebra.adjoin K {a}` is weakly étale over `K`.

This is the key descent lemma used to close the transcendental case of Stacks 092P
(`Algebra.WeaklyEtale.isSeparable_algebraic_of_isField`): once `K → K[a]` is
weakly étale, idempotency of `ker μ_{K[a]}` together with `K[a] ⊗_K K[a]` being
a domain (in the transcendental case) forces a contradiction.

**iter-021 status**: signature landed; auxiliary FG and injectivity lemmas proved
(see `kaehler_ideal_fg_adjoin`, `adjoinTensorIncl_injective`). The substantive
Stacks 092K descent of idempotency from `ker μ_L` (idempotent in the absolutely
flat ring `L ⊗_K L`) down to `ker μ_{K[a]}` inside the K-flat subring
`K[a] ⊗_K K[a] ↪ L ⊗_K L` remains as a typed `sorry`. The argument routes through
the explicit description of `ker μ_{K[a]}` as the ideal generated by the
diagonals `{1 ⊗ b − b ⊗ 1 : b ∈ A}` and uses that each such generator,
multiplied by the idempotent `e ∈ L ⊗_K L` exhibiting idempotency in the
overring, lands back in `A ⊗_K A` (the precise iter-020 gap). -/
theorem adjoin_singleton [Algebra.WeaklyEtale K L] :
    Algebra.WeaklyEtale K (Algebra.adjoin K ({a} : Set L)) := by
  -- Set `A := Algebra.adjoin K {a}` and split the `WeaklyEtale` structure into
  -- (1) `Module.Flat K A` and (2) `RingHom.Flat (lmul' K (S := A))`.
  set A : Subalgebra K L := Algebra.adjoin K ({a} : Set L) with _hA_def
  refine ⟨?_, ?_⟩
  · -- (1) Flatness of `K → A`: automatic because `K` is a field.
    exact inferInstance
  · -- (2) Flatness of `μ_A : A ⊗_K A → A`. Reduces (via the principal-ideal
    -- characterisation of pure ideals) to idempotency of
    -- `KaehlerDifferential.ideal K A`; this idempotency is the substantive
    -- Stacks 092K descent step, deferred to iter-022.
    --
    -- Ingredients in scope (mechanical):
    -- * `kaehler_ideal_fg_adjoin K L a` — FG of the kernel.
    -- * `adjoinTensorIncl_injective K L a` — the K-flat injection
    --   `A ⊗_K A ↪ L ⊗_K L` is injective.
    -- * `Ideal.Pure.of_isIdempotentElem` — FG + idempotent ⇒ pure.
    -- * `Module.Flat.of_linearEquiv` — transport flatness across
    --   `(A⊗A)/(ker μ) ≃ A`.
    --
    -- The descent (the sole iter-022 obligation): given the K-flat injection
    -- `i : A ⊗_K A ↪ L ⊗_K L`, the idempotent generator `e ∈ L ⊗_K L` of
    -- `KaehlerDifferential.ideal K L` (Stacks 092K input — `L ⊗_K L`
    -- absolutely flat via `absolutelyFlat_tensor_self`) restricts to a
    -- self-multiplication map on `i (A ⊗_K A)` that exhibits idempotency of
    -- `KaehlerDifferential.ideal K A` inside `A ⊗_K A`.
    have hker_FG : (KaehlerDifferential.ideal K
        (Algebra.adjoin K ({a} : Set L))).FG :=
      kaehler_ideal_fg_adjoin K L a
    -- Substantive Stacks 092K descent step.
    have hker_idem : IsIdempotentElem (KaehlerDifferential.ideal K
        (Algebra.adjoin K ({a} : Set L))) := by
      -- The strategy (Stacks 092K diagonal-generators route):
      -- (i)  Get an idempotent generator `e ∈ L ⊗ L` of `ker μ_L` from absolute
      --      flatness of `L ⊗_K L` (via `absolutelyFlat_tensor_self K L`).
      -- (ii) The K-flat injection `i : A⊗A ↪ L⊗L` (`adjoinTensorIncl_injective`)
      --      sends each diagonal `1⊗b - b⊗1 ∈ ker μ_A` to `1⊗b - b⊗1 ∈ ker μ_L`.
      -- (iii) Pull back the idempotency relation along `i` using injectivity.
      -- Steps (i) and (ii) are formalised explicitly below; the descent at
      -- step (iii) is the residual gap.
      classical
      haveI : Ring.AbsolutelyFlat (L ⊗[K] L) := absolutelyFlat_tensor_self K L
      -- The kernel `ker μ_L` is pure (since every ideal of an absolutely flat
      -- ring is pure).
      have hL_pure : (KaehlerDifferential.ideal K L).Pure :=
        Ring.AbsolutelyFlat.flat _
      -- Hence idempotent.
      have hL_idem : IsIdempotentElem (KaehlerDifferential.ideal K L) :=
        Ideal.isIdempotentElem_of_pure _
      -- Set up notation for the K-flat injection `i : A⊗A ↪ L⊗L`.
      let A' : Subalgebra K L := Algebra.adjoin K ({a} : Set L)
      let i : (A' ⊗[K] A') →ₐ[K] L ⊗[K] L :=
        Algebra.TensorProduct.map A'.val A'.val
      have hi_inj : Function.Injective i := adjoinTensorIncl_injective K L a
      -- `μ_L ∘ i = A'.val ∘ μ_A`: the multiplication map commutes with the
      -- inclusion of the subalgebra.
      have h_compat : ∀ x : A' ⊗[K] A',
          (Algebra.TensorProduct.lmul' (R := K) (S := L)) (i x) =
            A'.val ((Algebra.TensorProduct.lmul' (R := K) (S := A')) x) := by
        intro x
        induction x with
        | zero => simp
        | tmul s t => simp [i, Algebra.TensorProduct.map_tmul]
        | add x y hx hy => simp [map_add, hx, hy]
      -- `ker μ_A` maps into `ker μ_L` under `i`.
      have h_image_mem : ∀ x ∈ KaehlerDifferential.ideal K A',
          i x ∈ KaehlerDifferential.ideal K L := by
        intro x hx
        rw [RingHom.mem_ker] at hx ⊢
        simp [h_compat x, hx]
      -- **iter-024 principal-ideal route.** Since `A' = K[a]` is generated
      -- by the single element `a`, the kernel `ker μ_A'` is the principal
      -- ideal generated by `δ := 1 ⊗ a - a ⊗ 1`. Then `δ ∈ (Ideal.span {δ})²`
      -- reduces idempotency of the ideal to an element-level identity, and
      -- the L-side purity (`hL_pure`) combined with the K-flat projection
      -- `L⊗L → A'⊗A'` provides the witness.
      let aA : A' := ⟨a, Algebra.self_mem_adjoin_singleton K a⟩
      let δ : A' ⊗[K] A' := (1 : A') ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A')
      -- Step (i): the kernel is principal, generated by δ. (Helper lemma.)
      have hker_principal :
          KaehlerDifferential.ideal K A' = Ideal.span {δ} :=
        kaehler_ideal_adjoin_singleton_eq_span K L a
      -- Step (ii): δ ∈ (Ideal.span {δ})². This is the substantive descent
      -- obstacle: the L-side gives `δ_L ∈ (Ideal.span {δ_L})² ⊆ L⊗L` via
      -- absolute flatness (every element of an absolutely flat ring lies
      -- in its square), but the witness lives in `L⊗L`, and projecting it
      -- to a witness in `A'⊗A'` requires a K-linear retraction
      -- `r : L → A'` of the inclusion `A' ↪ L`, lifted to `r⊗r : L⊗L → A'⊗A'`.
      -- The K-linear complement of `A'` in `L` exists (every K-subspace
      -- splits), but turning this into an `A'⊗A'`-module retraction (so
      -- that `(r⊗r)(δ_L²·y_L) = δ²·(r⊗r)(y_L)`) requires `r` itself to be
      -- `A'`-linear, which generally fails when `L` is not `A'`-free
      -- (e.g., `L = K(a)` and `A' = K[a]` with `a` transcendental).
      -- A correct route uses a *finer* projection that exploits that
      -- `δ ∈ A'⊗A'` to land cross-summand contributions in the complement.
      -- This residual gap is the iter-025 obligation.
      have hidem_principal : δ ∈ (Ideal.span ({δ} : Set (A' ⊗[K] A'))) ^ 2 := by
        sorry
      -- Step (iii): conclude `IsIdempotentElem (KaehlerDifferential.ideal K A')`.
      rw [hker_principal]
      rw [IsIdempotentElem]
      rw [pow_two] at hidem_principal
      apply le_antisymm
      · -- `span {δ} * span {δ} ≤ span {δ}`.
        exact Ideal.mul_le_left
      · -- `span {δ} ≤ span {δ} * span {δ}` follows from `δ ∈ span {δ} * span {δ}`.
        rw [Ideal.span_le, Set.singleton_subset_iff]
        exact hidem_principal
    have hker_pure : (KaehlerDifferential.ideal K
        (Algebra.adjoin K ({a} : Set L))).Pure :=
      Ideal.Pure.of_isIdempotentElem hker_FG hker_idem
    -- From `(ker μ_A).Pure` deduce `RingHom.Flat (lmul' K (S := A))`.
    -- The factorisation `lmul' = e ∘ q` where `q : A⊗A → (A⊗A)⧸ker` is the
    -- quotient map and `e : (A⊗A)⧸ker ≃ A` is the first isomorphism gives
    -- `Flat (e ∘ q) = Flat q .comp Flat e`. `Flat q` is purity of the
    -- kernel; `Flat e` follows from `e` being a ring isomorphism.
    exact flat_lmul'_of_pure_ker (R := K) (S := A) hker_pure

end AdjoinSingleton

end Algebra.WeaklyEtale
