/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Proetale.Algebra.WeaklyEtaleField

/-!
# Weakly étale subalgebras of fields

This file formalises the field-to-field specialisation of Stacks
[092K](https://stacks.math.columbia.edu/tag/092K): if `K → L` is a weakly étale
extension of fields and `a ∈ L`, then the `K`-subalgebra `K[a] = Algebra.adjoin K {a}`
is again weakly étale over `K`.

## Main results

* `Algebra.WeaklyEtale.adjoin_singleton` —
  `K → Algebra.adjoin K {a}` is weakly étale when `K → L` is and `a ∈ L`.

## Proof strategy

The closure routes through Stacks 0CKR(3) / 15.105.8: every finitely generated
`K`-subalgebra of a weakly étale `K`-algebra (`K` a field) is étale over `K`,
hence weakly étale. The subalgebra `K[a] = Algebra.adjoin K {a}` is finitely
generated by the singleton `{a}`, so applying
`Algebra.WeaklyEtale.etale_of_fg` (housed in
`Proetale/Algebra/WeaklyEtaleField.lean`) yields the étale instance, from which
the weakly étale instance follows automatically.
-/

universe u

namespace Algebra.WeaklyEtale

variable (K L : Type u) [Field K] [Field L] [Algebra K L]

/-- **Stacks [092K], field-to-field specialisation.**

If `K → L` is a weakly étale extension of fields and `a ∈ L`, then the
`K`-subalgebra `K[a] = Algebra.adjoin K {a}` is weakly étale over `K`. -/
@[stacks 092K]
theorem adjoin_singleton [Algebra.WeaklyEtale K L] (a : L) :
    Algebra.WeaklyEtale K (Algebra.adjoin K ({a} : Set L)) := by
  have hFG : (Algebra.adjoin K ({a} : Set L)).FG :=
    Subalgebra.fg_def.mpr ⟨{a}, Set.finite_singleton _, rfl⟩
  have : Algebra.Etale K (Algebra.adjoin K ({a} : Set L)) :=
    Algebra.WeaklyEtale.etale_of_fg _ hFG
  infer_instance

end Algebra.WeaklyEtale
