/-
Copyright (c) 2026 The slopetale Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Proetale.Mathlib.RingTheory.WeaklyEtale.FieldExtension
import Mathlib.RingTheory.Ideal.Pure
import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.EssentialFiniteness
import Mathlib.RingTheory.Etale.Descent
import Mathlib.RingTheory.Ideal.Cotangent

/-!
# Weakly étale subalgebras of fields

This file formalises the field-to-field specialisation of Stacks
[092K](https://stacks.math.columbia.edu/tag/092K): if `K → L` is a weakly étale
extension of fields and `a ∈ L`, then the `K`-subalgebra `K[a] = Algebra.adjoin K {a}`
is again weakly étale over `K`.

The bivariate corollary closes the transcendental case of Stacks 092P (the consumer
`Algebra.WeaklyEtale.isAlgebraic_of_isField_aux` in `FieldExtension.lean`): once
`K → K[a]` is weakly étale and `a` is transcendental, `K[a] ⊗_K K[a] ≅ K[X, Y]` is
a domain whose multiplication kernel is the principal ideal `(X − Y)`, which is
neither `⊥` nor `⊤`, contradicting the idempotency forced by formal étaleness.

## Main results

* `Algebra.WeaklyEtale.adjoin_singleton` —
  `K → Algebra.adjoin K {a}` is weakly étale when `K → L` is and `a ∈ L`.

## Proof strategy (Stacks 092K, field-to-field case)

Write `A := Algebra.adjoin K {a}`. Recall `Algebra.WeaklyEtale K A` decomposes into:

1. **Flatness `K → A`**: automatic because `K` is a field; every `K`-module is free,
   hence flat.
2. **Flatness of `μ_A : A ⊗_K A → A`**: since `μ_A` is surjective with finitely
   generated kernel (`KaehlerDifferential.ideal K A` is FG by `EssFiniteType`),
   `RingHom.Flat μ_A` is equivalent to `(ker μ_A).Pure`, which by
   `Ideal.Pure.of_isIdempotentElem` reduces to `IsIdempotentElem (ker μ_A)`.

The idempotency in `A ⊗_K A` is the substantive Stacks 092K piece. It is inherited
from the absolutely flat overring `L ⊗_K L` along the `K`-flat injection
`A ⊗_K A ↪ L ⊗_K L`. iter-021 lands the infrastructure file and the auxiliary
lemmas; the full descent argument remains as a typed `sorry` (its precise strategy
is documented in the proof body).
-/

universe u

open scoped TensorProduct
open Algebra

namespace Algebra.WeaklyEtale

variable (K L : Type u) [Field K] [Field L] [Algebra K L]

section AdjoinSingleton

variable (a : L)

/-- The kernel `KaehlerDifferential.ideal K A` of the multiplication map
`A ⊗_K A → A` is finitely generated when `A = Algebra.adjoin K {a}`, because `A`
is essentially of finite type over `K` (generated by the single element `a`). -/
private lemma kaehler_ideal_fg_adjoin :
    (KaehlerDifferential.ideal K
      (Algebra.adjoin K ({a} : Set L))).FG := by
  haveI : Algebra.FiniteType K (Algebra.adjoin K ({a} : Set L)) :=
    Algebra.FiniteType.adjoin_of_finite (Set.finite_singleton a)
  haveI : Algebra.EssFiniteType K (Algebra.adjoin K ({a} : Set L)) :=
    Algebra.EssFiniteType.of_finiteType K _
  exact KaehlerDifferential.ideal_fg K _

/-- The inclusion `A ⊗_K A → L ⊗_K L` (where `A = Algebra.adjoin K {a}`) is
injective: `K`-flatness of `L` and `A` is automatic since `K` is a field, so the
tensor product of the inclusion `A ↪ L` with itself is injective. -/
private lemma adjoinTensorIncl_injective :
    Function.Injective
      (Algebra.TensorProduct.map
        (Algebra.adjoin K ({a} : Set L)).val
        (Algebra.adjoin K ({a} : Set L)).val :
          _ →ₐ[K] L ⊗[K] L) := by
  have hinj : Function.Injective
      ((Algebra.adjoin K ({a} : Set L)).val : _ → L) := Subtype.val_injective
  exact TensorProduct.map_injective_of_flat_flat _ _ hinj hinj

/-- For `A := Algebra.adjoin K {a}` inside `L`, the kernel of the multiplication
map `μ_A : A ⊗_K A → A` is the principal ideal generated by the diagonal
`δ := 1 ⊗ a - a ⊗ 1`. The "⊇" inclusion (containment) is `μ_A δ = 0`. The "⊆"
direction uses that every element of `A` is built from `a` via K-algebra
operations (`Algebra.adjoin_induction`); each diagonal `1 ⊗ b - b ⊗ 1` reduces
to a multiple of `δ` by telescoping (mem case), additivity, and the
multiplicative split
`1⊗(xy) - xy⊗1 = (1⊗x)(1⊗y - y⊗1) + (1⊗x - x⊗1)(y⊗1)`. -/
private lemma kaehler_ideal_adjoin_singleton_eq_span :
    letI A' : Subalgebra K L := Algebra.adjoin K ({a} : Set L)
    letI aA : A' := ⟨a, Algebra.self_mem_adjoin_singleton K a⟩
    KaehlerDifferential.ideal K A' =
      Ideal.span ({(1 : A') ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A')} :
        Set (A' ⊗[K] A')) := by
  set A' : Subalgebra K L := Algebra.adjoin K ({a} : Set L)
  set aA : A' := ⟨a, Algebra.self_mem_adjoin_singleton K a⟩
  set δ : A' ⊗[K] A' := (1 : A') ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A')
  refine le_antisymm ?_ ?_
  · rw [← KaehlerDifferential.span_range_eq_ideal]
    rw [Ideal.span_le]
    rintro _ ⟨b, rfl⟩
    obtain ⟨b', hb'⟩ := b
    suffices h : ∀ (y : L) (hy : y ∈ Algebra.adjoin K ({a} : Set L)),
        ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A') -
          (⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) ∈ Ideal.span ({δ} : Set (A' ⊗[K] A')) from
      h b' hb'
    intro y hy
    induction hy using Algebra.adjoin_induction with
    | mem x hx =>
      rw [Set.mem_singleton_iff] at hx
      subst hx
      exact Ideal.subset_span (Set.mem_singleton _)
    | algebraMap r =>
      have h0 : (1 : A') ⊗ₜ[K] (⟨algebraMap K L r,
          Subalgebra.algebraMap_mem _ _⟩ : A') -
          (⟨algebraMap K L r,
            Subalgebra.algebraMap_mem _ _⟩ : A') ⊗ₜ[K] (1 : A') = 0 := by
        have hval : (⟨algebraMap K L r,
            Subalgebra.algebraMap_mem _ _⟩ : A') = algebraMap K A' r := rfl
        rw [hval, Algebra.algebraMap_eq_smul_one,
          TensorProduct.tmul_smul, TensorProduct.smul_tmul', sub_self]
      rw [h0]
      exact Ideal.zero_mem _
    | add x y hx hy IHx IHy =>
      have hsum : (⟨x + y, add_mem hx hy⟩ : A') =
          (⟨x, hx⟩ : A') + (⟨y, hy⟩ : A') := rfl
      have heq : (1 : A') ⊗ₜ[K] (⟨x + y, add_mem hx hy⟩ : A') -
          (⟨x + y, add_mem hx hy⟩ : A') ⊗ₜ[K] (1 : A') =
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A') - (⟨x, hx⟩ : A') ⊗ₜ[K] (1 : A')) +
          ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A') - (⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) := by
        rw [hsum, TensorProduct.tmul_add, TensorProduct.add_tmul]
        abel
      rw [heq]
      exact Ideal.add_mem _ IHx IHy
    | mul x y hx hy IHx IHy =>
      have hmul : (⟨x * y, mul_mem hx hy⟩ : A') =
          (⟨x, hx⟩ : A') * (⟨y, hy⟩ : A') := rfl
      have h1 : ((1 : A') ⊗ₜ[K] ((⟨x, hx⟩ : A') * (⟨y, hy⟩ : A')) :
            A' ⊗[K] A') =
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A')) *
            ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A')) := by
        rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one]
      have h2 : (((⟨x, hx⟩ : A') * (⟨y, hy⟩ : A')) ⊗ₜ[K] (1 : A') :
            A' ⊗[K] A') =
          ((⟨x, hx⟩ : A') ⊗ₜ[K] (1 : A')) *
            ((⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) := by
        rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one]
      have heq : (1 : A') ⊗ₜ[K] (⟨x * y, mul_mem hx hy⟩ : A') -
          (⟨x * y, mul_mem hx hy⟩ : A') ⊗ₜ[K] (1 : A') =
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A')) *
            ((1 : A') ⊗ₜ[K] (⟨y, hy⟩ : A') -
              (⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) +
          ((1 : A') ⊗ₜ[K] (⟨x, hx⟩ : A') -
            (⟨x, hx⟩ : A') ⊗ₜ[K] (1 : A')) *
            ((⟨y, hy⟩ : A') ⊗ₜ[K] (1 : A')) := by
        rw [hmul, h1, h2]
        ring
      rw [heq]
      exact Ideal.add_mem _
        (Ideal.mul_mem_left _ _ IHy)
        (Ideal.mul_mem_right _ _ IHx)
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    show δ ∈ KaehlerDifferential.ideal K A'
    rw [KaehlerDifferential.ideal, RingHom.mem_ker]
    show Algebra.TensorProduct.lmul' (R := K) (S := A')
        ((1 : A') ⊗ₜ[K] aA - aA ⊗ₜ[K] (1 : A')) = 0
    rw [map_sub, Algebra.TensorProduct.lmul'_apply_tmul,
      Algebra.TensorProduct.lmul'_apply_tmul, one_mul, mul_one, sub_self]

/-- If the kernel of the multiplication map `μ : S ⊗[R] S → S` is a pure ideal,
then `μ : S ⊗[R] S →+* S` is flat. This is the standard step that converts
purity of `KaehlerDifferential.ideal R S` into flatness of `lmul'`. -/
private lemma flat_lmul'_of_pure_ker {R S : Type*} [CommRing R] [CommRing S]
    [Algebra R S] (hpure : (KaehlerDifferential.ideal R S).Pure) :
    (Algebra.TensorProduct.lmul' (R := R) (S := S)).toRingHom.Flat := by
  -- Unfold to `Module.Flat (S⊗S) S` under the `lmul'.toAlgebra` structure.
  rw [RingHom.Flat]
  letI : Algebra (S ⊗[R] S) S :=
    (Algebra.TensorProduct.lmul' (R := R) (S := S)).toRingHom.toAlgebra
  -- Under this algebra structure, `algebraMap (S⊗S) S = lmul'`.
  have h_alg : algebraMap (S ⊗[R] S) S =
      (Algebra.TensorProduct.lmul' (R := R) (S := S)).toRingHom := rfl
  -- `algebraMap` is (S⊗S)-linear (it's the algebraMap!), and surjective.
  have h_sur : Function.Surjective (Algebra.linearMap (S ⊗[R] S) S) := by
    intro x; exact ⟨x ⊗ₜ[R] 1, by simp [Algebra.linearMap, h_alg]⟩
  -- `LinearMap.ker (Algebra.linearMap _ _)` is the underlying submodule of
  -- `KaehlerDifferential.ideal R S`.
  have h_ker_eq : LinearMap.ker (Algebra.linearMap (S ⊗[R] S) S) =
      (KaehlerDifferential.ideal R S).restrictScalars (S ⊗[R] S) := by
    ext x
    simp [Algebra.linearMap, KaehlerDifferential.ideal, RingHom.mem_ker, h_alg]
  -- `LinearMap.quotKerEquivOfSurjective` gives a (S⊗S)-linear iso
  -- `(S⊗S) ⧸ LinearMap.ker(linearMap) ≃ₗ[S⊗S] S`.
  have hsur_iso :
      ((S ⊗[R] S) ⧸ LinearMap.ker (Algebra.linearMap (S ⊗[R] S) S))
        ≃ₗ[S ⊗[R] S] S :=
    LinearMap.quotKerEquivOfSurjective _ h_sur
  -- The underlying submodule of `KaehlerDifferential.ideal R S` (after
  -- `restrictScalars`) equals the LinearMap kernel, so the two quotients
  -- are the same.
  -- `hpure : Module.Flat (S⊗S) ((S⊗S) ⧸ KaehlerDifferential.ideal R S)`.
  -- That `Pure` is `Module.Flat (S⊗S) ((S⊗S) ⧸ I)` where the quotient is
  -- the ideal quotient. We need to transport to the submodule quotient.
  -- For ideals, `(R⧸I)` as a Ring with R-module structure coincides with
  -- the submodule quotient, so the two are definitionally equal.
  have h_flat_quot : Module.Flat (S ⊗[R] S)
      ((S ⊗[R] S) ⧸ LinearMap.ker (Algebra.linearMap (S ⊗[R] S) S)) := by
    rw [h_ker_eq]
    -- Now want `Module.Flat (S⊗S) ((S⊗S) ⧸ ((KaehlerDifferential.ideal R S).restrictScalars _))`.
    -- This is the same as `Pure (KaehlerDifferential.ideal R S)` up to identification.
    exact hpure
  exact Module.Flat.of_linearEquiv hsur_iso.symm

/-- **Stacks [092K], field-to-field specialisation.**

If `K → L` is a weakly étale extension of fields and `a ∈ L`, then the
`K`-subalgebra `K[a] = Algebra.adjoin K {a}` is weakly étale over `K`.

This is the key descent lemma used to close the transcendental case of Stacks 092P
(`Algebra.WeaklyEtale.isSeparable_algebraic_of_isField`): once `K → K[a]` is
weakly étale, idempotency of `ker μ_{K[a]}` together with `K[a] ⊗_K K[a]` being
a domain (in the transcendental case) forces a contradiction.

**iter-021 status**: signature landed; auxiliary FG and injectivity lemmas proved
(see `kaehler_ideal_fg_adjoin`, `adjoinTensorIncl_injective`). The substantive
Stacks 092K descent of idempotency from `ker μ_L` (idempotent in the absolutely
flat ring `L ⊗_K L`) down to `ker μ_{K[a]}` inside the K-flat subring
`K[a] ⊗_K K[a] ↪ L ⊗_K L` remains as a typed `sorry`. The argument routes through
the explicit description of `ker μ_{K[a]}` as the ideal generated by the
diagonals `{1 ⊗ b − b ⊗ 1 : b ∈ A}` and uses that each such generator,
multiplied by the idempotent `e ∈ L ⊗_K L` exhibiting idempotency in the
overring, lands back in `A ⊗_K A` (the precise iter-020 gap). -/
theorem adjoin_singleton [Algebra.WeaklyEtale K L] :
    Algebra.WeaklyEtale K (Algebra.adjoin K ({a} : Set L)) := by
  -- Set `A := Algebra.adjoin K {a}` and split the `WeaklyEtale` structure into
  -- (1) `Module.Flat K A` and (2) `RingHom.Flat (lmul' K (S := A))`.
  set A : Subalgebra K L := Algebra.adjoin K ({a} : Set L) with _hA_def
  refine ⟨?_, ?_⟩
  · -- (1) Flatness of `K → A`: automatic because `K` is a field.
    exact inferInstance
  · -- (2) Flatness of `μ_A : A ⊗_K A → A`. Reduces (via the principal-ideal
    -- characterisation of pure ideals) to idempotency of
    -- `KaehlerDifferential.ideal K A`; this idempotency is the substantive
    -- Stacks 092K descent step, deferred to iter-022.
    --
    -- Ingredients in scope (mechanical):
    -- * `kaehler_ideal_fg_adjoin K L a` — FG of the kernel.
    -- * `adjoinTensorIncl_injective K L a` — the K-flat injection
    --   `A ⊗_K A ↪ L ⊗_K L` is injective.
    -- * `Ideal.Pure.of_isIdempotentElem` — FG + idempotent ⇒ pure.
    -- * `Module.Flat.of_linearEquiv` — transport flatness across
    --   `(A⊗A)/(ker μ) ≃ A`.
    --
    -- The descent (the sole iter-022 obligation): given the K-flat injection
    -- `i : A ⊗_K A ↪ L ⊗_K L`, the idempotent generator `e ∈ L ⊗_K L` of
    -- `KaehlerDifferential.ideal K L` (Stacks 092K input — `L ⊗_K L`
    -- absolutely flat via `absolutelyFlat_tensor_self`) restricts to a
    -- self-multiplication map on `i (A ⊗_K A)` that exhibits idempotency of
    -- `KaehlerDifferential.ideal K A` inside `A ⊗_K A`.
    have hker_FG : (KaehlerDifferential.ideal K
        (Algebra.adjoin K ({a} : Set L))).FG :=
      kaehler_ideal_fg_adjoin K L a
    -- Substantive Stacks 092K descent step.
    have hker_idem : IsIdempotentElem (KaehlerDifferential.ideal K
        (Algebra.adjoin K ({a} : Set L))) := by
      -- **iter-025 pivot.** iter-024 documented the K-linear retraction
      -- route (`δ ∈ (Ideal.span {δ})²` via a K-linear splitting `L → A'`)
      -- as fundamentally blocked: any such retraction would have to be
      -- `A'`-linear to descend the multiplicative idempotency from `L⊗L`,
      -- and `A'`-linearity generally fails (e.g., when `L = K(a)` with `a`
      -- transcendental over `K[a]`).
      --
      -- The iter-025 pivot routes through
      -- `FormallyUnramified.of_formallyUnramified_tensorProduct_of_faithfullyFlat`
      -- with `T := L`, then converts `FormallyUnramified K A'` to
      -- `IsIdempotentElem (ker μ_A')` via the cotangent characterization
      -- `Ideal.cotangent_subsingleton_iff`.
      --
      -- The remaining substantive obligation is `FormallyUnramified L (L⊗A')`.
      -- Via `KaehlerDifferential.tensorKaehlerEquivBase` this is equivalent to
      -- `L ⊗_K Ω[A'/K] = 0`, and since `K → L` is faithfully flat (K field,
      -- L nonzero), the equivalence collapses to `Ω[A'/K] = 0`, i.e.,
      -- `FormallyUnramified K A'` itself. The descent route is therefore
      -- *equivalent* to the obligation, not strictly weaker — but it
      -- sharply localizes the substantive content into a single named
      -- `FormallyUnramified` instance, which the next iteration can attack
      -- via a non-descent strategy (e.g., direct calculation of `Ω[A'/K]`
      -- using the polynomial structure of `A' = K[a]`, or a refactor of
      -- the consumer `isAlgebraic_of_isField_aux` to bypass
      -- `adjoin_singleton` entirely).
      classical
      let A' : Subalgebra K L := Algebra.adjoin K ({a} : Set L)
      -- `K → L` is faithfully flat: K is a field and L is a nontrivial
      -- K-vector space, hence K-free.
      haveI hffKL : Module.FaithfullyFlat K L := inferInstance
      -- iter-025 sharply-localized residual obligation. The descent route
      -- isolates the substantive content here; full closure requires a
      -- non-descent strategy (see file-level task_result for the
      -- circularity finding).
      haveI hFU_LtA' : Algebra.FormallyUnramified L (L ⊗[K] A') := by
        sorry
      -- Apply the faithfully-flat descent:
      -- `FU L (L⊗_K A')` + `FaithfullyFlat K L` ⇒ `FU K A'`.
      haveI hFU_KA' : Algebra.FormallyUnramified K A' :=
        Algebra.FormallyUnramified.of_formallyUnramified_tensorProduct_of_faithfullyFlat L
      -- Convert `FormallyUnramified K A'` (= `Subsingleton Ω[A'/K]`) to
      -- `IsIdempotentElem (KaehlerDifferential.ideal K A')` via the
      -- cotangent characterization.
      exact (Ideal.cotangent_subsingleton_iff (KaehlerDifferential.ideal K A')).mp
        Algebra.FormallyUnramified.subsingleton_kaehlerDifferential
    have hker_pure : (KaehlerDifferential.ideal K
        (Algebra.adjoin K ({a} : Set L))).Pure :=
      Ideal.Pure.of_isIdempotentElem hker_FG hker_idem
    -- From `(ker μ_A).Pure` deduce `RingHom.Flat (lmul' K (S := A))`.
    -- The factorisation `lmul' = e ∘ q` where `q : A⊗A → (A⊗A)⧸ker` is the
    -- quotient map and `e : (A⊗A)⧸ker ≃ A` is the first isomorphism gives
    -- `Flat (e ∘ q) = Flat q .comp Flat e`. `Flat q` is purity of the
    -- kernel; `Flat e` follows from `e` being a ring isomorphism.
    exact flat_lmul'_of_pure_ker (R := K) (S := A) hker_pure

end AdjoinSingleton

end Algebra.WeaklyEtale
